# Generated by Django 2.2.3 on 2019-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField()),
                ('app_name', models.CharField(max_length=30)),
                ('company_email', models.CharField(max_length=50)),
                ('email_token', models.CharField(max_length=50)),
            ],
        ),
    ]
